"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const companies_controller_1 = require("../controllers/companies.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
router.get('/', companies_controller_1.getAllCompanies);
router.get('/:id', companies_controller_1.getCompanyById);
router.post('/', auth_middleware_1.authenticate, companies_controller_1.createCompany);
exports.default = router;
