"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const jobs_controller_1 = require("../controllers/jobs.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
router.get('/search', jobs_controller_1.searchJobs);
router.get('/', jobs_controller_1.getAllJobs);
router.get('/:id', jobs_controller_1.getJobById);
router.post('/', auth_middleware_1.authenticate, jobs_controller_1.createJob);
router.delete('/:id', auth_middleware_1.authenticate, jobs_controller_1.deleteJob);
exports.default = router;
